# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-15 14:54
from __future__ import unicode_literals

from django.db import migrations

CHANNELS_TO_CREATE = [
    '/',
    '/outer-space',
    '/jokes',
    '/music'
]


def forwards(apps, schema_editor):
    Channel = apps.get_model('messageboard', 'Channel')
    for channel_name in CHANNELS_TO_CREATE:
        Channel.objects.get_or_create(name=channel_name)


def backwards(apps, schema_editor):
    Channel = apps.get_model('messageboard', 'Channel')
    Channel.objects.filter(name__in=CHANNELS_TO_CREATE).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards)
    ]
