# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-15 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0002_create_initial_channels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set([('title', 'channel')]),
        ),
    ]
