# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-16 01:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0003_auto_20170415_1052'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='like',
            old_name='message',
            new_name='topic',
        ),
    ]
