# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-04-16 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messageboard', '0005_auto_20170416_1100'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topic',
            unique_together=set([]),
        ),
    ]
